# https://github.com/marketplace/actions/flutter-action
# https://github.com/marketplace/actions/cancel-workflow-action

name: deploymaent

on:
  push:
    branches:
      - master

jobs:
  UnitTest:
    runs-on: ubuntu-18.04

  WidgetTest:
    runs-on: ubuntu-18.04
    

  Build:
    needs: [UnitTest, WidgetTest]
    runs-on: ubuntu-18.04

  Deployt:
    needs: [Build]
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2 
        with:
          flutter-version: "3.3.10"
          channel: "stable"
      - run: flutter test
